export const GET_POSTS_BOOKMARKS_REQUEST = 'GET_POSTS_BOOKMARKS_REQUEST';
export const GET_POSTS_BOOKMARKS_SUCCESS = 'GET_POSTS_BOOKMARKS_SUCCESS';

export const GET_COMMENTS_BOOKMARKS_SUCCESS = 'GET_COMMENTS_BOOKMARKS_SUCCESS';
