export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const GET_COMMENT_REPLIES_SUCCESS = 'GET_COMMENT_REPLIES_SUCCESS';


export const OPEN_COMMENTS_MODAL = 'OPEN_COMMENTS_MODAL';
export const CLOSE_COMMENTS_MODAL = 'CLOSE_COMMENTS_MODAL';