export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';

export const GET_SINGLE_POST_VOTES_SUCCESS = 'GET_SINGLE_POST_VOTES_SUCCESS';
export const GET_RECENT_POSTS_SUCCESS = 'GET_RECENT_POSTS_SUCCESS';
