export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';
export const GET_SINGLE_POST_EDITDATA_SUCCESS = 'GET_SINGLE_POST_EDITDATA_SUCCESS';
export const CLEAR_SINGLE_POST = 'CLEAR_SINGLE_POST';

export const GET_SINGLE_POST_VOTES_SUCCESS = 'GET_SINGLE_POST_VOTES_SUCCESS';
export const GET_RECENT_POSTS_SUCCESS = 'GET_RECENT_POSTS_SUCCESS';

export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS';
export const SET_POST_EDIT = 'SET_POST_EDIT';

export const MODIFY_POSTS_REQUEST = 'MODIFY_POSTS_REQUEST';
export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';

export const WITHOUT_EDITION_POSTS_SUCCESS = 'WITHOUT_EDITION_POSTS_SUCCESS';
