export const FETCH_CHANNEL_REQUEST = 'FETCH_CHANNEL_REQUEST';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_FAILURE = 'FETCH_CHANNEL_FAILURE';

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const FETCH_FOLLOWERS_REQUEST = 'FETCH_FOLLOWERS_REQUEST';
export const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS';
export const FETCH_FOLLOWERS_FAILURE = 'FETCH_FOLLOWERS_FAILURE';

export const FETCH_FOLLOWINGS_SUCCESS = 'FETCH_FOLLOWINGS_SUCCESS';

export const FOLLOW_CHANNEL_REQUEST = 'FOLLOW_CHANNEL_REQUEST';
export const FOLLOW_CHANNEL_SUCCESS = 'FOLLOW_CHANNEL_SUCCESS';
export const FOLLOW_CHANNEL_FAILURE = 'FOLLOW_CHANNEL_FAILURE';

export const UNFOLLOW_CHANNEL_REQUEST = 'UNFOLLOW_CHANNEL_REQUEST';
export const UNFOLLOW_CHANNEL_SUCCESS = 'UNFOLLOW_CHANNEL_SUCCESS';
export const UNFOLLOW_CHANNEL_FAILURE = 'UNFOLLOW_CHANNEL_FAILURE';


export const FETCH_USER_CHANNEL = 'FETCH_USER_CHANNEL';
