export const FOLLOW_CHANEL = 'FOLLOW_CHANNEL'
export const GET_CHANNEL_DATA = 'GET_CHANNEL_DATA';
export const GET_CHANNEL_POSTS = 'GET_CHANNEL_POSTS';
export const FOLLOW_CHANNEL = 'FOLLOW_CHANNEL'
export const UNFOLLOW_CHANNEL = 'UNFOLLOW_CHANNEL'
export const GET_FOLLOWINGS = 'GET_FOLLOWINGS'