
export const CREATE_EDITION_REQUEST = 'CREATE_EDITION_REQUEST';
export const CREATE_EDITION_SUCCESS = 'CREATE_EDITION_SUCCESS';

export const GET_EDITIONS_REQUEST = 'GET_EDITIONS_REQUEST';
export const GET_EDITIONS_SUCCESS = 'GET_EDITIONS_SUCCESS';

export const GET_SINGLE_EDITION_REQUEST = 'GET_SINGLE_EDITION_REQUEST';
export const GET_SINGLE_EDITION_SUCCESS = 'GET_SINGLE_EDITION_SUCCESS';

export const GET_USER_EDITION_REQUEST = 'GET_USER_EDITION_REQUEST';
export const GET_USER_EDITION_SUCCESS = 'GET_USER_EDITION_SUCCESS';

export const UPLOAD_PDF_PROGRESS = 'UPLOAD_PDF_PROGRESS';

export const CLEAN_EDITION = 'CLEAN_EDITION';
