export const CREATE_EDITION_REQUEST = 'CREATE_EDITION_REQUEST';
export const CREATE_EDITION_SUCCESS = 'CREATE_EDITION_SUCCESS';

export const GET_EDITIONS_REQUEST = 'GET_EDITIONS_REQUEST';
export const GET_EDITIONS_SUCCESS = 'GET_EDITIONS_SUCCESS';

export const GET_SINGLE_EDITION_REQUEST = 'GET_SINGLE_EDITION_REQUEST';
export const GET_SINGLE_EDITION_SUCCESS = 'GET_SINGLE_EDITION_SUCCESS';

export const GET_USER_EDITION_REQUEST = 'GET_USER_EDITION_REQUEST';
export const GET_USER_EDITION_SUCCESS = 'GET_USER_EDITION_SUCCESS';

export const UPLOAD_PDF_PROGRESS = 'UPLOAD_PDF_PROGRESS';

export const CLEAN_EDITION = 'CLEAN_EDITION';

  // Library Image Actions
  export const GET_LIBRARY_IMAGES_REQUEST = 'GET_LIBRARY_IMAGES_REQUEST';
  export const GET_LIBRARY_IMAGES_SUCCESS = 'GET_LIBRARY_IMAGES_SUCCESS';
  export const GET_LIBRARY_IMAGES_FAILURE = 'GET_LIBRARY_IMAGES_FAILURE';
  export const UPLOAD_LIBRARY_IMAGE_REQUEST = 'UPLOAD_LIBRARY_IMAGE_REQUEST';
  export const UPLOAD_LIBRARY_IMAGE_SUCCESS = 'UPLOAD_LIBRARY_IMAGE_SUCCESS';
  export const UPLOAD_LIBRARY_IMAGE_FAILURE = 'UPLOAD_LIBRARY_IMAGE_FAILURE';